service: conch-app-js-rest-api

frameworkVersion: '2'

# API Naming Conventions 
# Article Reference: https://blog.stoplight.io/crud-api-design

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: 'us-east-1'
functions:
  pulse:
    handler: src/pulse.pulse
    events:
      - http:
          path: /
          method: get

  list:
    handler: src/todos/list.list
    events:
      - httpApi:
          path: /todos
          method: get

  get:
    handler: src/todos/get.get
    events:
      - httpApi:
          path: /todos/{fromUser}
          method: get

  queryby:
    handler: src/todos/queryby.queryby
    events:
      - httpApi:
          path: /query/{fromUser} 
          method: get

  getalltransactions:
    handler: src/transactions/getAllTransactions.getAllTransactions
    events:
      - httpApi:
          path: /items/one/{fromUser}
          method: get
      - httpApi:
          path: /items/all
          method: get

  createtransactions:
    handler: src/transactions/createTransactions.createTransactions
    events:
      - httpApi:
          path: /items/{id}
          method: DELETE 
      - httpApi:
          path: /items 
          method: PUT
      - httpApi:
          path: /items 
          method: POST

  getallnominaentries:
    handler: src/sersalud/getAllNominaEntries.getAllNominaEntries
    events:
      - httpApi:
          path: /nomina/one/{timestamp}
          method: get
      - httpApi:
          path: /nomina/all
          method: get 

  createnominaentry:
    handler: src/sersalud/createNominaEntry.createNominaEntry
    events:
      - httpApi:
          path: /entries/{timestamp}
          method: DELETE 
      - httpApi:
          path: /entries 
          method: PUT
      - httpApi:
          path: /entries 
          method: POST

  getallresources:
    handler: src/sersalud/getAllResources.getAllResources
    events:
      - httpApi:
          path: /resources/one/{timestamp}
          method: get
      - httpApi:
          path: /resources/all
          method: get

  createresourceentry:
    handler: src/sersalud/createResourceEntry.createResourceEntry
    events:
      - httpApi:
          path: /resources/{nombre}
          method: DELETE 
      - httpApi:
          path: /resources 
          method: PUT
      - httpApi:
          path: /resources 
          method: POST

  bulkresourceentries:
    handler: src/sersalud/bulkResourceEntries.bulkResourceEntries
    events:
      - httpApi:
          path: /resources/bulk 
          method: PUT

  bulknominaentries:
    handler: src/sersalud/bulkNominaEntries.bulkNominaEntries
    events:
      - httpApi:
          path: /nomina/bulk
          method: PUT

  getallpuestos:
    handler: src/sersalud/getAllPuestos.getAllPuestos
    events:
      - httpApi:
          path: /puestos/all
          method: get

