service: conch-app-js-rest-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: 'us-east-1'
functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get   
 